// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/limiter.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RefillRate    int32                  `protobuf:"varint,3,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Request) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Request) GetRefillRate() int32 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_api_limiter_proto protoreflect.FileDescriptor

const file_api_limiter_proto_rawDesc = "" +
	"\n" +
	"\x11api/limiter.proto\x12\alimiter\"_\n" +
	"\aRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vrefill_rate\x18\x03 \x01(\x05R\n" +
	"refillRate\"$\n" +
	"\bResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2A\n" +
	"\vRateLimiter\x122\n" +
	"\vShouldAllow\x12\x10.limiter.Request\x1a\x11.limiter.ResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_limiter_proto_rawDescOnce sync.Once
	file_api_limiter_proto_rawDescData []byte
)

func file_api_limiter_proto_rawDescGZIP() []byte {
	file_api_limiter_proto_rawDescOnce.Do(func() {
		file_api_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_limiter_proto_rawDesc), len(file_api_limiter_proto_rawDesc)))
	})
	return file_api_limiter_proto_rawDescData
}

var file_api_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_limiter_proto_goTypes = []any{
	(*Request)(nil),  // 0: limiter.Request
	(*Response)(nil), // 1: limiter.Response
}
var file_api_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.RateLimiter.ShouldAllow:input_type -> limiter.Request
	1, // 1: limiter.RateLimiter.ShouldAllow:output_type -> limiter.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_limiter_proto_init() }
func file_api_limiter_proto_init() {
	if File_api_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_limiter_proto_rawDesc), len(file_api_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_limiter_proto_goTypes,
		DependencyIndexes: file_api_limiter_proto_depIdxs,
		MessageInfos:      file_api_limiter_proto_msgTypes,
	}.Build()
	File_api_limiter_proto = out.File
	file_api_limiter_proto_goTypes = nil
	file_api_limiter_proto_depIdxs = nil
}
